/********************************************************************************************************
 * @file    test_nvheal.c
 *
 * @brief   Host regression for the real light/moes_nvheal.c and the private
 *          byte-read length guard in light/moes_nvitems.h.
 *
 * The simulated records use Telink's actual 4-byte sector header, 8-byte
 * index, 8-byte item header, absolute payload offset, and two CRC fields. The
 * tests therefore exercise the production parser rather than a source copy.
 *******************************************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "shim/tl_common.h"
#include "../../light/moes_nvitems.h"
#include "../../light/moes_nvheal.h"

#define FLASH_SIZE             0x100000u
#define NV_REGION_START        0xD8000u
#define NV_REGION_END          0xE8000u
#define APP_START              0xE4000u
#define SECTOR_SIZE            0x1000u
#define MODULE_INFO_SIZE       0x200u
#define OWNER_MAGIC            0x4D4F4553u

#define SECTOR_VALID_CRC       0x7A7Au
#define ITEM_VALID_SINGLE      0x7Au
#define ITEM_INVALID           0x50u
#define HEADER_VALID_CRC       0x7Au

typedef struct {
	u16 usedFlag;
	u8 idName;
	u8 opSect;
} sector_t;

typedef struct {
	u32 offset;
	u16 size;
	u8 itemId;
	u8 usedState;
} index_t;

typedef struct {
	u32 checkSum;
	u16 size;
	u8 itemId;
	u8 used;
} header_t;

static u8 flashImage[FLASH_SIZE];
static u16 nextIndex[2];
static u32 nextPayload[2];
static int eraseCount;

static int writeCount;
static u8 writeSingle;
static u16 writeModule;
static u8 writeItem;
static u16 writeLen;
static u8 writePayload[8];

static nv_sts_t sizeStatus;
static u16 reportedSize;
static int readCalls;
static u8 readValue;

static int failures;

#define CHECK(cond, ...) do {                                                \
		if(!(cond)){                                                         \
			failures++;                                                      \
			printf("    FAIL  " __VA_ARGS__);                                \
			printf("\n          at %s:%d: %s\n", __FILE__, __LINE__, #cond);   \
		}                                                                    \
	} while(0)

/* Bitwise form of Telink utility.c's reflected CRC32 table operation. The
 * canary below fixes the polynomial/init contract independently of records
 * generated by this same helper. */
u32 xcrc32(const u8 *buf, int len, u32 init)
{
	u32 crc = init;

	while(len-- > 0){
		crc ^= *buf++;
		for(u8 bit = 0; bit < 8; bit++){
			crc = (crc >> 1) ^ ((crc & 1) ? 0xEDB88320u : 0);
		}
	}
	return crc;
}

static void bounds(u32 addr, u32 len)
{
	if(addr > FLASH_SIZE || len > FLASH_SIZE - addr){
		fprintf(stderr, "flash bounds violation: 0x%08x + %u\n", addr, len);
		abort();
	}
}

void flash_read(u32 addr, u32 len, u8 *buf)
{
	bounds(addr, len);
	memcpy(buf, &flashImage[addr], len);
}

void flash_erase(u32 addr)
{
	if((addr & (SECTOR_SIZE - 1)) != 0){
		fprintf(stderr, "unaligned erase: 0x%08x\n", addr);
		abort();
	}
	bounds(addr, SECTOR_SIZE);
	memset(&flashImage[addr], 0xFF, SECTOR_SIZE);
	eraseCount++;
}

nv_sts_t nv_flashWriteNew(u8 single, u16 id, u8 itemId, u16 len, u8 *buf)
{
	writeCount++;
	writeSingle = single;
	writeModule = id;
	writeItem = itemId;
	writeLen = len;
	if(len > sizeof(writePayload)){
		abort();
	}
	memcpy(writePayload, buf, len);
	return NV_SUCC;
}

nv_sts_t nv_flashSingleItemSizeGet(u8 id, u8 itemId, u16 *len)
{
	(void)id;
	(void)itemId;
	if(sizeStatus == NV_SUCC){
		*len = reportedSize;
	}
	return sizeStatus;
}

nv_sts_t nv_flashReadNew(u8 single, u8 id, u8 itemId, u16 len, u8 *buf)
{
	(void)single;
	(void)id;
	(void)itemId;
	(void)len;
	readCalls++;
	*buf = readValue;
	return NV_SUCC;
}

static void resetEnvironment(void)
{
	memset(flashImage, 0xFF, sizeof(flashImage));
	memset(nextIndex, 0, sizeof(nextIndex));
	nextPayload[0] = APP_START + MODULE_INFO_SIZE;
	nextPayload[1] = APP_START + SECTOR_SIZE + MODULE_INFO_SIZE;
	eraseCount = 0;
	writeCount = 0;
	writeSingle = 0;
	writeModule = 0;
	writeItem = 0;
	writeLen = 0;
	memset(writePayload, 0, sizeof(writePayload));
	sizeStatus = NV_ITEM_NOT_FOUND;
	reportedSize = 0;
	readCalls = 0;
	readValue = 0;
}

static void initSector(u8 sectorNo)
{
	sector_t sector;
	u8 crcBytes[2] = { NV_MODULE_APP, sectorNo };
	u32 start = APP_START + (u32)sectorNo * SECTOR_SIZE;
	u32 crc = xcrc32(crcBytes, sizeof(crcBytes), 0xFFFFFFFFu);

	memset(&flashImage[start], 0xFF, SECTOR_SIZE);
	sector.usedFlag = SECTOR_VALID_CRC;
	sector.idName = NV_MODULE_APP;
	sector.opSect = (u8)(((crc & 0x3F) << 2) | sectorNo);
	memcpy(&flashImage[start], &sector, sizeof(sector));
	nextIndex[sectorNo] = 0;
	nextPayload[sectorNo] = start + MODULE_INFO_SIZE;
}

/* Return the absolute address of the item header. */
static u32 addRecord(u8 sectorNo, u8 itemId, const void *payload, u16 len,
					 u8 indexState)
{
	index_t index;
	header_t header;
	u8 meta[4];
	u32 sectorStart = APP_START + (u32)sectorNo * SECTOR_SIZE;
	u32 indexAddr = sectorStart + sizeof(sector_t) +
	                (u32)nextIndex[sectorNo] * sizeof(index_t);
	u32 crc;

	if(nextPayload[sectorNo] + sizeof(header) + len > sectorStart + SECTOR_SIZE){
		abort();
	}

	index.offset = nextPayload[sectorNo];
	index.size = (u16)(sizeof(header) + len);
	index.itemId = itemId;
	index.usedState = indexState;

	header.size = len;
	header.itemId = itemId;
	header.used = HEADER_VALID_CRC;

	crc = xcrc32(payload, len, 0xFFFFFFFFu);
	meta[0] = (u8)(len & 0xFF);
	meta[1] = (u8)(len >> 8);
	meta[2] = itemId;
	meta[3] = header.used;
	crc = xcrc32(meta, sizeof(meta), crc);
	header.checkSum = crc & 0xFFFF;
	crc = xcrc32((const u8 *)&index, sizeof(index) - 1, 0xFFFFFFFFu);
	header.checkSum |= (crc & 0xFFFF) << 16;

	memcpy(&flashImage[indexAddr], &index, sizeof(index));
	memcpy(&flashImage[index.offset], &header, sizeof(header));
	memcpy(&flashImage[index.offset + sizeof(header)], payload, len);

	nextIndex[sectorNo]++;
	nextPayload[sectorNo] = (index.offset + index.size + 3) & ~3u;
	return index.offset;
}

static void checkOwnerWrite(const char *name)
{
	u32 owner = 0;

	memcpy(&owner, writePayload, sizeof(owner));
	CHECK(writeCount == 1, "%s: expected one owner write, got %d", name, writeCount);
	CHECK(writeSingle == 1, "%s: owner must be a single item", name);
	CHECK(writeModule == NV_MODULE_APP, "%s: owner module %u", name, writeModule);
	CHECK(writeItem == MOES_NV_ITEM_OWNER, "%s: owner item 0x%02x", name, writeItem);
	CHECK(writeLen == 4, "%s: owner length %u", name, writeLen);
	CHECK(owner == OWNER_MAGIC, "%s: owner value 0x%08x", name, owner);
}

static void expectHeal(const char *name)
{
	moes_nvHealPreStack();
	CHECK(eraseCount == 16, "%s: expected 16 sector erases, got %d", name, eraseCount);
	moes_nvHealPostStack();
	checkOwnerWrite(name);
}

static void expectMigration(const char *name)
{
	moes_nvHealPreStack();
	CHECK(eraseCount == 0, "%s: legacy custom NV was erased", name);
	moes_nvHealPostStack();
	checkOwnerWrite(name);
}

static void testCrcCanary(void)
{
	static const u8 text[] = "123456789";
	CHECK(xcrc32(text, 9, 0xFFFFFFFFu) == 0x340BC6D9u,
	      "CRC32 implementation does not match Telink's reflected contract");
}

static void testBlankStockHeals(void)
{
	resetEnvironment();
	expectHeal("blank stock APP module");
}

static void testLegacyYoungMigrates(void)
{
	u8 young = 1;
	resetEnvironment();
	initSector(0);
	addRecord(0, MOES_NV_ITEM_BOOT_YOUNG, &young, 1, ITEM_VALID_SINGLE);
	expectMigration("valid legacy young marker");
}

static void testCapturedLegacyYoungMigrates(void)
{
	/* Sanitized bytes from the actual post-conversion APP capture at absolute
	 * 0xE4000: sector header, active index at +0x1C, item at +0x224. No device
	 * identity or network material is present in this nine-byte item. */
	static const u8 sector[] = { 0x7A, 0x7A, 0x06, 0x18 };
	static const u8 index[] = { 0x24, 0x42, 0x0E, 0x00, 0x09, 0x00, 0x72, 0x7A };
	static const u8 item[] = { 0xD1, 0xEC, 0x97, 0x03, 0x01, 0x00, 0x72, 0x7A, 0x00 };

	resetEnvironment();
	memcpy(&flashImage[APP_START], sector, sizeof(sector));
	memcpy(&flashImage[APP_START + 0x1C], index, sizeof(index));
	memcpy(&flashImage[APP_START + 0x224], item, sizeof(item));
	expectMigration("captured legacy young record");
}

static void testLegacyProbationMigrates(void)
{
	u8 count = 3;
	resetEnvironment();
	initSector(0);
	addRecord(0, MOES_NV_ITEM_BOOT_PROBATION, &count, 1, ITEM_VALID_SINGLE);
	expectMigration("valid legacy probation marker");
}

static void testOutOfRangeYoungHeals(void)
{
	u8 young = 2;
	resetEnvironment();
	initSector(0);
	addRecord(0, MOES_NV_ITEM_BOOT_YOUNG, &young, 1, ITEM_VALID_SINGLE);
	expectHeal("out-of-range legacy young marker");
}

static void testOutOfRangeProbationHeals(void)
{
	u8 count = 7;
	resetEnvironment();
	initSector(0);
	addRecord(0, MOES_NV_ITEM_BOOT_PROBATION, &count, 1, ITEM_VALID_SINGLE);
	expectHeal("out-of-range legacy probation marker");
}

static void testBuild30InvalidOwnerMigrates(void)
{
	u32 owner = OWNER_MAGIC;
	resetEnvironment();
	initSector(0);
	addRecord(0, MOES_NV_ITEM_SKIP_RST, &owner, 4, ITEM_INVALID);
	expectMigration("invalidated Build 30 owner");
}

static void testCapturedBuild30CollisionMigrates(void)
{
	/* Verbatim bytes from the ceiling fixture captured 2026-08-31 at absolute
	 * 0xE4000, after Build 30 had wedged it. Both records share item 0x70: the
	 * four-byte owner is invalid in the index (0x50) because the one-byte
	 * reset-skip write superseded it, and the reset-skip itself is valid.
	 * Nothing here carries device identity or network material - the payloads
	 * are the ASCII magic "MOES" and a single zero byte. */
	static const u8 sector[]    = { 0x7A, 0x7A, 0x06, 0x18 };
	static const u8 idxOwner[]  = { 0x00, 0x42, 0x0E, 0x00, 0x0C, 0x00, 0x70, 0x50 };
	static const u8 idxSkip[]   = { 0x18, 0x42, 0x0E, 0x00, 0x09, 0x00, 0x70, 0x7A };
	static const u8 recOwner[]  = { 0xAF, 0xDC, 0xDF, 0xBD, 0x04, 0x00, 0x70, 0x7A,
	                                0x53, 0x45, 0x4F, 0x4D };
	static const u8 recSkip[]   = { 0x53, 0x8E, 0x9D, 0xAD, 0x01, 0x00, 0x70, 0x7A,
	                                0x00 };

	resetEnvironment();
	memcpy(&flashImage[APP_START],          sector,   sizeof(sector));
	memcpy(&flashImage[APP_START + 0x004],  idxOwner, sizeof(idxOwner));
	memcpy(&flashImage[APP_START + 0x014],  idxSkip,  sizeof(idxSkip));
	memcpy(&flashImage[APP_START + 0x200],  recOwner, sizeof(recOwner));
	memcpy(&flashImage[APP_START + 0x218],  recSkip,  sizeof(recSkip));

	/* The valid one-byte reset-skip must not shadow the invalidated owner. */
	expectMigration("captured Build 30 owner/reset-skip collision");
}

static void testCurrentOwnerIsNoOp(void)
{
	u32 owner = OWNER_MAGIC;
	resetEnvironment();
	initSector(1);
	addRecord(1, MOES_NV_ITEM_OWNER, &owner, 4, ITEM_VALID_SINGLE);
	moes_nvHealPreStack();
	moes_nvHealPostStack();
	CHECK(eraseCount == 0, "current owner erased NV");
	CHECK(writeCount == 0, "current owner caused a redundant write");
}

static void testResetSkipIsNotAnOwner(void)
{
	u8 skip = 1;
	resetEnvironment();
	initSector(0);
	addRecord(0, MOES_NV_ITEM_SKIP_RST, &skip, 1, ITEM_VALID_SINGLE);
	expectHeal("one-byte reset skip is not ownership");
}

static void testRawMagicIsNotAnOwner(void)
{
	u32 owner = OWNER_MAGIC;
	resetEnvironment();
	memcpy(&flashImage[APP_START + 0x300], &owner, sizeof(owner));
	expectHeal("unindexed raw magic is not ownership");
}

static void testCorruptLegacyCrcHeals(void)
{
	u8 young = 1;
	u32 headerAddr;
	resetEnvironment();
	initSector(0);
	headerAddr = addRecord(0, MOES_NV_ITEM_BOOT_YOUNG, &young, 1, ITEM_VALID_SINGLE);
	flashImage[headerAddr + sizeof(header_t)] ^= 1;
	expectHeal("corrupt legacy payload CRC");
}

static void testInvalidLegacyRecordHeals(void)
{
	u8 young = 1;
	resetEnvironment();
	initSector(0);
	addRecord(0, MOES_NV_ITEM_BOOT_YOUNG, &young, 1, ITEM_INVALID);
	expectHeal("invalid legacy record");
}

static void testWrongOwnerMagicHeals(void)
{
	u32 wrong = 0x12345678u;
	resetEnvironment();
	initSector(0);
	addRecord(0, MOES_NV_ITEM_OWNER, &wrong, 4, ITEM_VALID_SINGLE);
	expectHeal("wrong current owner magic");
}

static void testBadSectorCrcHeals(void)
{
	u8 young = 1;
	resetEnvironment();
	initSector(0);
	addRecord(0, MOES_NV_ITEM_BOOT_YOUNG, &young, 1, ITEM_VALID_SINGLE);
	flashImage[APP_START + 3] ^= 0x04;
	expectHeal("bad sector CRC");
}

static void testExactByteReadRejectsFourByteRecord(void)
{
	u8 value = 0xA5;
	nv_sts_t status;

	resetEnvironment();
	sizeStatus = NV_SUCC;
	reportedSize = 4;
	readValue = 0x53;
	status = moes_nvReadByteExact(MOES_NV_ITEM_SKIP_RST, &value);
	CHECK(status == NV_ITEM_LEN_NOT_MATCH, "four-byte record status %d", status);
	CHECK(readCalls == 0, "wrong-length record reached unsafe SDK read");
	CHECK(value == 0xA5, "wrong-length record modified destination");

	reportedSize = 1;
	status = moes_nvReadByteExact(MOES_NV_ITEM_SKIP_RST, &value);
	CHECK(status == NV_SUCC, "one-byte record status %d", status);
	CHECK(readCalls == 1, "one-byte record did not reach SDK read");
	CHECK(value == 0x53, "one-byte read value 0x%02x", value);
}

int main(void)
{
	testCrcCanary();
	testBlankStockHeals();
	testLegacyYoungMigrates();
	testCapturedLegacyYoungMigrates();
	testLegacyProbationMigrates();
	testOutOfRangeYoungHeals();
	testOutOfRangeProbationHeals();
	testBuild30InvalidOwnerMigrates();
	testCapturedBuild30CollisionMigrates();
	testCurrentOwnerIsNoOp();
	testResetSkipIsNotAnOwner();
	testRawMagicIsNotAnOwner();
	testCorruptLegacyCrcHeals();
	testInvalidLegacyRecordHeals();
	testWrongOwnerMagicHeals();
	testBadSectorCrcHeals();
	testExactByteReadRejectsFourByteRecord();

	if(failures){
		printf("nvheal host test: %d failure(s)\n", failures);
		return 1;
	}
	printf("nvheal host test: all 17 scenarios passed\n");
	return 0;
}
